image_config: &image_config

  IMAGE_NAME: any_image_name

  IMAGE_TAG: any_tag_name

  LINUX_VERSION: UBUNTU_XENIAL

  RUBY_VERSION_NUM: 2.3.1

  JAVA: false

  MYSQL_CLIENT: false

  POSTGRES_CLIENT: true

  DOCKERIZE: true

  BROWSERS: true

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config

    steps:
    - checkout

    - run: bash scripts/generate.sh > Dockerfile

    - run: gem install bundler

    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

    - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
